version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "lambda-layer-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-8q5x3b8wepjv"
s3_prefix = "lambda-layer-dev"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ENV=\"dev\""

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "lambda-layer-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-8q5x3b8wepjv"
s3_prefix = "lambda-layer-prod"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ENV=\"prod\""